### ISSUE TITLE
Completing reoccuring tasks

### ISSUE THREAD

**Issue by gnu-nix** [ddksr/cliist#1]
Hello Žiga, 

Thank you very much for this client. I noticed that once a reoccurring task is marked as completed via cliist, the task in its entirety is completed. This happens even if the task should be "recreated" with a new due date (weekly or daily tasks for example). 

Is there any method of completing a reoccurring task without simply updating the due date or completing the entire task? 

Thank you for your time,
gnu-nix

**Comment by ddksr** [comment]
Hello gnu-nix,

first of all, big thank you for the feedback, truly appreciated. I'm really happy I'm not the only user of this simple client.
You have a good point, I have never tried to complete a reoccurring task before via cliist. I will check this out and get back to you ASAP. 

Best, 
Žiga

**Comment by ddksr** [comment]
Hello @gnu-nix 

I have found a workaround (ecd8327d90ebbe26e39cce4e6568d6b548d4a990) for the recurring tasks. But I had to implement some kind of cache because the client is asynchronous. The recurring task will need to appear in the last listing command used.

I've updated the [readme](README.md) with examples. 

Please pull and update the settings file for the latest features. 

And again, thank you for the report.

Best, 
ddksr
