### ISSUE TITLE
401 Unauthorized - How do I get an API key?

### ISSUE THREAD

**Issue by conatus** [ddksr/cliist#4]
Hi there,

Thanks very much for the client.

I generated a test token from the developer interface after creating an application and it doesn't appear to be working.

Is this the correct procedure for setting this stuff up? Is there somewhere else I am supposed to be obtaining this from?

**Comment by ddksr** [comment]
you get the auth token from Todoist->top right settings menu->Account->API token
Using the install script should work just fine ... are you using a premium account? it's been quite some time since I last tested it on a normal account and it could be that it is not working any more. I will check.

Thank you
best,
Žiga

**Comment by conatus** [comment]
Works great, thanks so much. Will add this to the readme when I get a spare moment.

Its a normal account and works fine.

**Comment by ddksr** [comment]
OK great! thank you for the info, if you notice any strange behavior with cliist, please don't hesitate to open an issue.

Thanks again!
